volumes/exceleryweb/exceleryweb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

volumes/exceleryweb/main/urls.py
from django.urls import path
from .views import ImportFileView, LoginView, SignupView, LogoutView

app_name = 'main'
urlpatterns = [
    path('', ImportFileView.as_view(), name='home'),
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('logout', LogoutView.as_view(), name='logout'),
]

volumes/exceleryweb/templates/components/nav-bar.html
<nav>
    <div class="container mx-auto mobile-menu-item bg-gray-200 rounded-md">
        <a class="flex items-center mr-1 font-bold text-orange-600" href="{% url 'main:home' %}">
            <img class="max-w-8 max-h-8" src="./images/file-engine.png" alt="">
            خانه
        </a>
        <div class="hidden md:flex gap-x-5 items-center text-gray-600">
            <a class="link-gray" href="{% url 'main:home' %}">
                <i class="fa-regular fa-house"></i>
                <span class="mr-1">خانه</span>
            </a>
            <a class="link-gray" href="">
                <i class="fa-brands fa-github"></i>
                <span class="mr-1">گیت هاب</span>
            </a>
            <a class="link-gray" href="">
                <i class="fa-solid fa-file-circle-info"></i>
                <span class="mr-1">درباره</span>
            </a>
            {% if request.user.is_authenticated %}
            <a class="link-gray" href="{% url 'main:logout' %}">
                <i class="fa-solid fa-arrow-right-to-bracket mt-2"></i>
                <span class="mr-1">خروج</span>
            </a>
            {% endif %}
        </div>
        <button onclick="toggleElementId('user-simple-menu');toggleHideElementId('user-menu-chevron-down');toggleHideElementId('user-menu-chevron-up')" class="hidden md:flex items-center border-2 border-gray-400 p-1 rounded-md hover:bg-yellow-300 hover:border-yellow-500">
            <i id="user-menu-chevron-down" class="fa-solid fa-chevron-down ml-1" style="display: none;"></i>
            <i id="user-menu-chevron-up" class="fa-solid fa-chevron-up ml-1"></i>
            <span class="ml-1 font-bold text-stone-600">مهرداد محمودی نژاد</span>
            <img class="w-10 h-10 rounded-full" src="./images/user-default-icon.png" alt="">
        </button>
        <ul id="user-simple-menu" class="dropdown">
            <li class="dropdown-item"><a href="">ایتم یک</a></li>
            <li class="dropdown-item"><a href="">ایتم دو</a></li>
            <li class="dropdown-item"><a href="">ایتم سه</a></li>
            <li class="dropdown-item"><a href="">ایتم چهار</a></li>
        </ul>

        <button onclick="toggleElementId('mobile-menu')" class="md:hidden">
            <i class="fa-solid fa-bars"></i>
            <!-- <i class="fa-solid fa-x"></i> -->
        </button>

        <!-- Mobile menu -->
        <div id="mobile-menu" class="hidden fixed container mx-auto inset-0 bg-gray-200 rounded-md">
            <div class="mobile-menu-item">
                <a class="flex items-center mr-1 font-bold text-orange-600" href="{% url 'main:home' %}">
                    <img class="max-w-8 max-h-8" src="./images/file-engine.png" alt="">
                    خانه
                </a>
                <button onclick="toggleElementId('mobile-menu')" class="md:hidden">
                    <i class="fa-solid fa-bars"></i>
                    <!-- <i class="fa-solid fa-x"></i> -->
                </button>
            </div>
            <div class="m-4 text-gray-600 border-y-2 py-2 border-gray-400">
                <a class="mobile-menu-bg-yellow" href="{% url 'main:home' %}">
                    <i class="fa-regular fa-house"></i>
                    <span class="mr-2">خانه</span>
                </a>
                <a class="mobile-menu-bg-yellow" href="">
                    <i class="fa-brands fa-github"></i>
                    <span class="mr-2">گیت هاب</span>
                </a>
                <a class="mobile-menu-bg-yellow" href="">
                    <i class="fa-solid fa-file-circle-info"></i>
                    <span class="mr-2">درباره</span>
                </a>
                {% if request.user.is_authenticated %}
                <a class="mobile-menu-bg-yellow" href="{% url 'main:logout' %}">
                    <i class="fa-solid fa-arrow-right-to-bracket mt-2"></i>
                    <span class="mr-2">خروج</span>
                </a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>

volumes/exceleryweb/templates/components/sidbar.html
<div id="sidbar" class="border min-h-[80vh] xl:w-1/5 w-1/5 md:flex hidden border-gray-400 rounded-lg p-3">
    <ul class="text-center w-full">
        <a href="{% url 'main:home' %}">
            <li class="sidbar-item-active">
                Import file
            </li>
        </a>
        <a href="./export.html">
            <li class="sidbar-item">
                Export file
            </li>
        </a>
        
        {% if request.user.is_authenticated %}
        <a href="{% url 'main:logout' %}">
            <li class="sidbar-item">
                Logout
            </li>
        </a>
        {% else %}
        <a href="{% url 'main:signup' %}">
            <li class="sidbar-item">
                Login | Signup
            </li>
        </a>
        {% endif %}
    </ul>
</div>
<!-- Main -->
<div id="main" class="border-2 overflow-x-scroll h-[80vh] border-gray-300 bg-gray-200 rounded-lg xl:w-3/5 w-full p-3">